options:
  logging: CLOUD_LOGGING_ONLY  

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'us-central1-docker.pkg.dev/nicoservertest/service-job-trigger/service-job-run-trigger:$COMMIT_SHA',
        '.'
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'us-central1-docker.pkg.dev/nicoservertest/service-job-trigger/service-job-run-trigger:$COMMIT_SHA'
      ]

images:
  - 'us-central1-docker.pkg.dev/nicoservertest/service-job-trigger/service-job-run-trigger:$COMMIT_SHA'